# Generated by Django 3.1.4 on 2021-01-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
