# Generated by Django 3.1.4 on 2021-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpart', '0002_auto_20210103_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='currency',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
